# Generated by Django 3.1.2 on 2020-10-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('phoneNo', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('watchprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tiggered', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('action', models.CharField(max_length=30)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dateBought', models.CharField(max_length=30)),
                ('orignialUnitBought', models.PositiveIntegerField()),
                ('unitSold', models.PositiveIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
        ),
    ]
