# Generated by Django 3.1.2 on 2020-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currentUnit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='tiggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dateBuy',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='dateSell',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
