# Generated by Django 3.1.2 on 2020-10-22 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('phoneNo', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBuy', models.DateTimeField()),
                ('dateSell', models.DateTimeField()),
                ('unitBuy', models.PositiveIntegerField()),
                ('unitSell', models.PositiveIntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.user')),
            ],
        ),
    ]
