# Generated by Django 3.1.2 on 2020-10-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_auto_20201022_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='unitBuy',
            new_name='UnitSold',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='unitSell',
            new_name='orignialUnitBought',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='currentUnit',
        ),
    ]
