# Generated by Django 3.1.2 on 2020-10-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_auto_20201022_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='code',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='code',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='code',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
    ]
