# Generated by Django 3.1.2 on 2020-10-22 12:58

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0005_auto_20201022_2249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchList',
            new_name='WatchListItem',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='orignialUnitBought',
            new_name='originalUnitsBought',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='unitSold',
            new_name='unitsSold',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
